version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3001:3001"
    depends_on:
      - auth-service
      - user-service
      - product-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "3002:3002"

  user-service:
    build: ./services/user-service
    ports:
      - "3003:3003"

  product-service:
    build: ./services/product-service
    ports:
      - "3004:3004"